In [1]:
import numpy as np

In [2]:
t1 = np.arange(16)
t1 = np.random.randint(20, size=(4,4))
print t1

[[11 18  1 10]
 [ 1 18 11  5]
 [ 0 18 16  0]
 [12 10 16 19]]


In [3]:
t1 = t1 * (np.argsort(np.argsort(t1)) >= (t1.shape[1]-2))
print t1

[[11 18  0  0]
 [ 0 18 11  0]
 [ 0 18 16  0]
 [ 0  0 16 19]]


In [5]:
%time a=np.true_divide(t1.sum(1), (t1!=0).sum(1))
print a

CPU times: user 80 µs, sys: 79 µs, total: 159 µs
Wall time: 125 µs
[14.5 14.5 17.  17.5]


In [11]:
%time b= np.nanmean(np.where((t1 == 0), np.nan, t1), axis=1)
print b

CPU times: user 137 µs, sys: 125 µs, total: 262 µs
Wall time: 235 µs
[14.5 14.5 17.  17.5]
